2025/04/06 07:10:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:10:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:10:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:10:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:10:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:10:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:11:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:11:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:11:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:11:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:11:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:11:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:12:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:12:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:12:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:12:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:12:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:12:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:13:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:13:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:13:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:13:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:13:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:13:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:14:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:14:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:14:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:14:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:14:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:14:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:15:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:15:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:15:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:15:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:15:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:15:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:16:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:16:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:16:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:16:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:16:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:16:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:17:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:17:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:17:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:17:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:17:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:17:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:18:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:18:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:18:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:18:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:18:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:18:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:19:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:19:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:19:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:19:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:19:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:19:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:20:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:20:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:20:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:20:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:20:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:20:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:21:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:21:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:21:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:21:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:21:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:21:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:22:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:22:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:22:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:22:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:22:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:22:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:23:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:23:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:23:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:23:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:23:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:23:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:24:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:24:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:24:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:24:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:24:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:24:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:25:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:25:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:25:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:25:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:25:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:25:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:26:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:26:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:26:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:26:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:26:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:26:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:27:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:27:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:27:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:27:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:27:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:27:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:28:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:28:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:28:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:28:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:28:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:28:53 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:29:03 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:29:13 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:29:23 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:29:33 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:29:43 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:29:53 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:30:03 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:30:13 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:30:23 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:30:33 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:30:43 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:30:53 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:31:03 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:31:13 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:31:23 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:31:33 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:31:43 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:31:53 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:32:03 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:32:13 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:32:23 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:32:33 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:32:43 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:32:53 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:33:03 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:33:13 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:33:23 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:33:33 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:33:43 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:33:53 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:34:03 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:34:13 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:34:23 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:34:33 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:34:43 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:34:53 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:35:03 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:35:13 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:35:23 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:35:33 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:35:43 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:35:53 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:36:03 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:36:13 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:36:23 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:36:33 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:36:43 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:36:53 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:37:03 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:37:13 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:37:23 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:37:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:37:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:38:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:38:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:38:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:38:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:38:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:38:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:39:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:39:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:39:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:39:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:39:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:39:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:40:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:40:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:40:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:40:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:40:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:40:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:41:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:41:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:41:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:41:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:41:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:41:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:42:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:42:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:42:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:42:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:42:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:42:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:43:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:43:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:43:23 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:43:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:43:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:43:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:44:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:44:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:44:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:44:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:44:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:44:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:45:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:45:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:45:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:45:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:45:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:45:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:46:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:46:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:46:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:46:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:46:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:46:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:47:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:47:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:47:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:47:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:47:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:47:44 [error] 25#25: *68 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "OPTIONS /territories/hierarchy HTTP/1.1", upstream: "http://192.168.65.254:33000/territories/hierarchy", host: "localhost:3000", referrer: "http://localhost:4000/"
2025/04/06 07:47:44 [error] 24#24: *71 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "OPTIONS /forecast/67ad6a7c-c259-4912-a497-8784ab9c00c1/history?forecastId=67ad6a7c-c259-4912-a497-8784ab9c00c1 HTTP/1.1", upstream: "http://192.168.65.254:33000/forecast/67ad6a7c-c259-4912-a497-8784ab9c00c1/history?forecastId=67ad6a7c-c259-4912-a497-8784ab9c00c1", host: "localhost:3000", referrer: "http://localhost:4000/"
2025/04/06 07:47:44 [error] 24#24: *72 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "OPTIONS /forecast/prev-and-current-budget?forecastId=67ad6a7c-c259-4912-a497-8784ab9c00c1&forecastCalendarId=959f35ad-04b1-4fb3-a2d6-ad618332e848&currentForecastYear=2025 HTTP/1.1", upstream: "http://192.168.65.254:33000/forecast/prev-and-current-budget?forecastId=67ad6a7c-c259-4912-a497-8784ab9c00c1&forecastCalendarId=959f35ad-04b1-4fb3-a2d6-ad618332e848&currentForecastYear=2025", host: "localhost:3000", referrer: "http://localhost:4000/"
2025/04/06 07:47:44 [error] 24#24: *70 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "OPTIONS /forecast?page=1&pageSize=100&search= HTTP/1.1", upstream: "http://192.168.65.254:33000/forecast?page=1&pageSize=100&search=", host: "localhost:3000", referrer: "http://localhost:4000/"
2025/04/06 07:47:44 [error] 24#24: *69 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "OPTIONS /forecast?page=1&pageSize=100&search= HTTP/1.1", upstream: "http://192.168.65.254:33000/forecast?page=1&pageSize=100&search=", host: "localhost:3000", referrer: "http://localhost:4000/"
2025/04/06 07:47:44 [error] 24#24: *73 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "OPTIONS /login_check HTTP/1.1", upstream: "http://192.168.65.254:33000/login_check", host: "localhost:3000", referrer: "http://localhost:4000/"
2025/04/06 07:47:44 [error] 24#24: *72 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "OPTIONS /forecast/budget?page=1&pageSize=9007199254740991&forecastId=67ad6a7c-c259-4912-a497-8784ab9c00c1&territoryId=db737f09-19f0-4ca2-b618-82d872e7d71e&search=&forecastCalendarId=959f35ad-04b1-4fb3-a2d6-ad618332e848&isExec=false&isProjected=true HTTP/1.1", upstream: "http://192.168.65.254:33000/forecast/budget?page=1&pageSize=9007199254740991&forecastId=67ad6a7c-c259-4912-a497-8784ab9c00c1&territoryId=db737f09-19f0-4ca2-b618-82d872e7d71e&search=&forecastCalendarId=959f35ad-04b1-4fb3-a2d6-ad618332e848&isExec=false&isProjected=true", host: "localhost:3000", referrer: "http://localhost:4000/"
2025/04/06 07:47:44 [error] 24#24: *70 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "OPTIONS /forecast/budget?page=1&pageSize=9007199254740991&forecastId=67ad6a7c-c259-4912-a497-8784ab9c00c1&territoryId=db737f09-19f0-4ca2-b618-82d872e7d71e&search=&forecastCalendarId=959f35ad-04b1-4fb3-a2d6-ad618332e848&isExec=true&isProjected=true HTTP/1.1", upstream: "http://192.168.65.254:33000/forecast/budget?page=1&pageSize=9007199254740991&forecastId=67ad6a7c-c259-4912-a497-8784ab9c00c1&territoryId=db737f09-19f0-4ca2-b618-82d872e7d71e&search=&forecastCalendarId=959f35ad-04b1-4fb3-a2d6-ad618332e848&isExec=true&isProjected=true", host: "localhost:3000", referrer: "http://localhost:4000/"
2025/04/06 07:47:47 [error] 26#26: *88 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /favicon.ico HTTP/1.1", upstream: "http://192.168.65.254:33000/favicon.ico", host: "localhost:3000", referrer: "http://localhost:3000/metrics"
2025/04/06 07:47:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:48:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:48:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:48:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:48:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:48:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:48:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:49:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:49:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:49:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:49:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:49:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:49:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:50:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:50:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:50:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:50:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:50:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:50:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:51:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:51:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:51:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:51:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:51:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:51:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:52:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:52:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:52:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:52:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:52:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:52:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:53:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:53:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:53:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:53:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:53:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:53:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:54:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:54:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:54:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:54:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:54:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:54:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:55:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
