2025/04/06 07:10:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:10:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:10:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:10:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:10:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:10:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:11:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:11:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:11:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:11:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:11:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:11:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:12:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:12:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:12:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:12:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:12:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:12:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:13:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:13:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:13:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:13:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:13:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:13:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:14:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:14:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:14:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:14:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:14:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:14:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:15:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:15:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:15:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:15:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:15:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:15:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:16:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:16:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:16:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:16:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:16:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:16:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:17:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:17:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:17:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:17:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:17:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:17:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:18:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:18:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:18:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:18:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:18:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:18:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:19:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:19:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:19:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:19:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:19:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:19:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:20:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:20:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:20:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:20:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:20:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:20:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:21:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:21:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:21:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:21:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:21:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:21:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:22:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:22:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:22:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:22:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:22:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:22:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:23:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:23:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:23:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:23:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:23:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:23:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:24:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:24:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:24:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:24:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:24:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:24:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:25:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:25:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:25:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:25:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:25:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:25:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:26:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:26:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:26:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:26:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:26:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:26:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:27:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:27:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:27:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:27:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:27:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:27:52 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:28:02 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:28:12 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:28:22 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:28:32 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:28:42 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:28:53 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:29:03 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:29:13 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:29:23 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:29:33 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:29:43 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:29:53 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:30:03 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:30:13 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:30:23 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:30:33 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:30:43 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:30:53 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:31:03 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:31:13 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:31:23 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:31:33 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:31:43 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:31:53 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:32:03 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:32:13 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:32:23 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:32:33 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:32:43 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:32:53 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:33:03 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:33:13 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:33:23 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:33:33 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:33:43 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:33:53 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:34:03 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:34:13 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:34:23 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
2025/04/06 07:34:33 [error] 23#23: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: dev.local, request: "GET /metrics HTTP/1.1", upstream: "http://192.168.65.254:33000/metrics", host: "host.docker.internal:3000"
